# Generated by Django 6.0 on 2026-01-12 22:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_webhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, help_text='Coupon applied to this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='payment.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, help_text='Coupon code used (stored for reference)', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount from coupon', max_digits=10),
        ),
    ]
